---
title: "FunOlympics Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    theme: flatly
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(lubridate)
library(plotly)
library(DT)
library(readr)
```

```{r global, include=FALSE}
data <- readr::read_csv("log_data.csv")

# convert time to character
data$time <- as.character(data[["time"]])

# convert time column to time-stamp
data$time <- as.POSIXct(data$time, format = "%H:%M:%S")

# count the number of requests per hour
hourly_requests <- data %>%
  group_by(time = floor_date(time, 'hour')) %>%
  summarize(n = n())


# grouping status codes --> successful and failed
data <- data %>% 
  mutate(
    # create new 'request_success' column 
    request_success = dplyr::case_when(
      status_code == 200 | status_code == 304 ~ "Successful",
      status_code == 404 | status_code == 500 ~ "Failed"
    ),
    # convert to factor
    request_success = factor(
      request_success,
      level = c("Successful", "Failed")
    )
  )

# count the number of successful requests
successful_requests <- data %>%
  filter(request_success == "Successful") %>%
  summarize(n = n())

# count the number of failed requests
failed_requests <- data %>%
  filter(request_success == "Failed") %>%
  summarize(n = n())

# count the number of requests per continent
continent_requests <- data %>%
  filter(!is.na(continent)) %>%
  group_by(continent) %>%
  summarize(n = n())

# count the number of requests per country
country_requests <- data %>%
  group_by(country) %>%
  summarize(n = n())


# create aliases for URL paths
data <- data %>% 
  mutate(
    # create new 'sporting_event' column
    sporting_event = dplyr::case_match(
      path,
      "/basketball.php" ~ "Basketball",
      "/table-tennis.php" ~ "Table Tennis",
      "/tennis.php" ~ "Tennis",
      "/athletics/track.php" ~ "Athletics - Track",
      "/athletics/field.php" ~ "Athletics - Field",
      "/volleyball.php" ~ "Volleyball",
      "/cycling.php" ~ "Cycling",
      "/diving.php" ~ "Diving",
      "/gymnastics.php" ~ "Gymnastics",
      "/weightlifting.php" ~ "Weightlifting",
      "/rowing.php" ~ "Rowing",
      "/football.php" ~ "Football",
      "/swimming.php" ~ "Swimming",
      "/water-polo.php" ~ "Water Polo",
      "/wrestling.php" ~ "Wrestling",
      "/karate.php" ~ "Karate"
    ))

# count the number of requests for each sporting event
path_requests <- data %>%
  filter(!is.na(sporting_event)) %>%
  group_by(sporting_event) %>%
  summarize(n = n())

# count the number of requests by gender
gender_requests <- data %>%
  group_by(gender) %>%
  summarize(n = n())

# grouping users into age groups
data <- data %>% 
  mutate(
    # create new 'age_group' column
    age_group = dplyr::case_when(
      age <= 24             ~ "16-24",
      age >= 25 & age <= 34 ~ "25-34",
      age >= 35 & age <= 44 ~ "35-44",
      age >= 45 & age <= 54 ~ "45-54",
      age >= 55 & age <= 64 ~ "55-64",
      age >= 65             ~ "65+"
    ),
    # convert to factor
    age_group = factor(
      age_group,
      level = c("16-24", "25-34","35-44", "45-54", "55-64", "65+")
    )
  )

# count the number of requests by age group
age_requests <- data %>%
  group_by(age_group) %>%
  summarize(n = n())
```


Home 
===============================================

Inputs {.sidebar data-width=170}
-----------------------------------------------
```{r}
# filter level drop-down filter
selectInput("filter_level",
            "Filter Level:",
            choices = c("Country", "Continent"),
            selected = "Continent")
```

<hr/>

```{r}
# country and continent drop-down filter depending on selected filter level
output$filter_dropdown <- renderUI({
  if (input$filter_level == "Country") {
    selectInput("country_select",
                "Country:",
                choices = country_requests$country)
  } else {
    selectInput("continent_select",
                "Continent:",
                choices = continent_requests$continent)
  }
})

uiOutput("filter_dropdown")
```

```{r}
# sporting event drop-down filter
selectInput("sport_select",
            "Sporting Event:",
            choices = path_requests$sporting_event,
            selected = path_requests$sporting_event[[1]])
```


Row 
-----------------------------------------------

###

```{r}
# value box displaying the total number of requests
renderValueBox({
  count_requests <- nrow(data)
  valueBox("Total Requests", value = count_requests, color = "#326fa8")
})
```

###

```{r}
# value box displaying the total number of successful requests
renderValueBox({
  succ_requests <- successful_requests$n
  valueBox("Succesful Requests", value = succ_requests, color = "#32a875")
})
```

###

```{r}
# value box displaying the total number of failed requests
renderValueBox({
  fail_requests <- failed_requests$n
  valueBox("Failed Requests", value = fail_requests, color = "#a83244")
})
```


Row 
--------------------------------------------------

### Average Viewership per Time of Day

```{r}
renderPlotly({
  filtered_data <- data
  
  # filter data depending on user selected filter level
  if (input$filter_level == "Country") {
    filtered_data <- filtered_data %>%
      filter(country %in% input$country_select)
  } else {
    filtered_data <- filtered_data %>%
      filter(continent %in% input$continent_select)
  }
  
  hourly_requests <- filtered_data %>%
    group_by(time = floor_date(time, 'hour')) %>%
    summarize(n = n())
  
  # generate interactive line plot
  plot_ly(hourly_requests, type = "scatter", mode = "lines", x = ~time, y = ~n) %>%
    layout(
      showlegend = FALSE, 
      xaxis = list(title = "Time", 
                   rangeslider = list(visible = TRUE), 
                   zerolinecolor = "#FFFF",
                   zerolinewidth = 2,
                   gridcolor = "#FFFF"), 
      yaxis = list(title = "Requests",
                   zerolinecolor = "#FFFF",
                   zerolinewidth = 2,
                   gridcolor = "#FFFF"),
      plot_bgcolor = "#E5ECF6"
    )
})
```


Row 
----------------------------------------------------------

### Viewership Preference of Sporting Events

```{r fig.width=8}
renderPlotly({
  filtered_data <- data
  
  # filter data depending on user selected filter level
  if (input$filter_level == "Country") {
    filtered_data <- filtered_data %>%
      filter(country %in% input$country_select)
  } else {
    filtered_data <- filtered_data %>%
      filter(continent %in% input$continent_select)
  }
  
  path_requests <- filtered_data %>%
    filter(!is.na(sporting_event)) %>%
    group_by(sporting_event) %>%
    summarize(n = n())
  
  # generate interactive bar plot
  plot_ly(path_requests, type = "bar", x = ~n, y = ~sporting_event) %>%
    layout(
      showlegend = FALSE,
      xaxis = list(title = 'Requests'),
      yaxis = list(title = 'Sporting Events'), 
      barmode = 'group')
})
```

### Average Viewership by Age

```{r}
renderPlotly({
  filtered_data <- data
  
  # filter data depending on user selected filter level
  if (input$filter_level == "Country") {
    filtered_data <- filtered_data %>%
      filter(country %in% input$country_select,
             sporting_event %in% input$sport_select)
  } else {
    filtered_data <- filtered_data %>%
      filter(continent %in% input$continent_select,
             sporting_event %in% input$sport_select)
  }
  
  age_requests <- filtered_data %>%
    group_by(age_group) %>%
    summarize(n = n())
  
  # generate interactive bar plot
  plot_ly(age_requests, type = "bar", color = ~age_group, x = ~age_group, y = ~n) %>%
    layout(
      showlegend = FALSE,
      xaxis = list(title = 'Age Group'),
      yaxis = list(title = 'Requests')
    )
})
```

### Average Viewership by Gender 

```{r fig.width=7}
renderPlotly({
  filtered_data <- data
  
  # filter data depending on user selected filter level
  if (input$filter_level == "Country") {
    filtered_data <- filtered_data %>%
      filter(country %in% input$country_select,
             sporting_event %in% input$sport_select)
  } else {
    filtered_data <- filtered_data %>%
      filter(continent %in% input$continent_select,
             sporting_event %in% input$sport_select)
  }
  
  gender_requests <- filtered_data %>%
    group_by(gender) %>%
    summarize(n = n())
  
  # generate interactive doughnut chart
  plot_ly(gender_requests, labels = ~gender, values = ~n) %>%
    add_pie(hole = 0.6)
})
```


Map
================================================

Inputs {.sidebar data-width=170}
-----------------------------------------------

```{r}
# sporting event drop-down filter
selectInput("sport_select_map",
            "Sporting Event:",
            choices = path_requests$sporting_event,
            selected = path_requests$sporting_event[[1]])
```

Row 
------------------------------------------------

### Average Viewership per Country

```{r fig.width=10, fig.height=5.3}
renderPlotly({
  filtered_data <- data %>%
    filter(sporting_event %in% input$sport_select_map)
  
  country_requests <- filtered_data %>%
    group_by(country) %>%
    summarize(n = n())
  
  # generate interactive choropleth map
  plot_geo( 
    data = country_requests,
    z = ~n, 
    locationmode = "country names",  
    locations = ~country,
    text = ~paste(country, '<br>', 'Total Visits: ', n),
    marker = list(line = list(color = "black", width = 0.6))
  ) %>% colorbar(title = "Visits")
})
```

Concurrent Sporting Events
===================================================

Inputs {.sidebar data-width=200}
-----------------------------------------------

Select two sporting events to compare their viewership numbers at different times of the day.

<hr/>

```{r}
# sporting event drop-down filter
selectInput("concurrent_sport_select1",
            "Sporting Event 1:",
            choices = path_requests$sporting_event,
            selected = path_requests$sporting_event[[1]])
```

```{r}
# sporting event drop-down filter
selectInput("concurrent_sport_select2",
            "Sporting Event 2:",
            choices = path_requests$sporting_event,
            selected = path_requests$sporting_event[[2]])
```

<hr/>

```{r}
# filter level drop-down filter
selectInput("concurrent_filter_level",
            "Filter Level:",
            choices = c("Country", "Continent"),
            selected = "Continent")
```

<hr/>

```{r}
# # country and continent drop-down filter depending on selected filter level
output$concurrent_filter_dropdown <- renderUI({
  if (input$concurrent_filter_level == "Country") {
    selectInput("concurrent_country_select",
                "Country:",
                choices = country_requests$country)
  } else {
    selectInput("concurrent_continent_select",
                "Continent:",
                choices = continent_requests$continent)
  }
})

uiOutput("concurrent_filter_dropdown")
```

Row
---------------------------------------------------

### Viewership Preference for Concurrently Running Sporting Events

```{r}
renderPlotly({
  filtered_data <- data
  
  # filter data depending on user selected filter level
  if (input$concurrent_filter_level == "Country") {
    filtered_data <- filtered_data %>%
      filter(country %in% input$concurrent_country_select,
             sporting_event %in% c(input$concurrent_sport_select1, input$concurrent_sport_select2))
  } else {
    filtered_data <- filtered_data %>%
      filter(continent %in% input$concurrent_continent_select,
             sporting_event %in% c(input$concurrent_sport_select1, input$concurrent_sport_select2))
  }
  
  concurrent_hourly_requests <- filtered_data %>%
    group_by(sporting_event, time = floor_date(time, 'hour')) %>%
    summarize(n = n())
  
  # generate interactive line plot
  plot_ly(concurrent_hourly_requests, type = "scatter", mode = "lines", x = ~time, y = ~n, color = ~sporting_event, colors = c("#325ea8", "#a83e32")) %>%
    layout(
      showlegend = TRUE, 
      xaxis = list(title = "Time", 
                   rangeslider = list(visible = TRUE), 
                   zerolinecolor = "#FFFF",
                   zerolinewidth = 2,
                   gridcolor = "#FFFF"), 
      yaxis = list(title = "Requests",
                   zerolinecolor = "#FFFF",
                   zerolinewidth = 2,
                   gridcolor = "#FFFF"),
      plot_bgcolor = "#E5ECF6"
    )
})
```


Data
===================================================

Row {data-height=535}
---------------------------------------------------

###

```{r}
# display interactive data table
DT::renderDataTable({
  DT::datatable(data = readr::read_csv("log_data.csv"),
               rownames = F,
               colnames = c("time", "ip_address", "request_method",
                            "path", "status_code", "country",
                            "continent", "gender", "age"),
               extensions = "Buttons",
               options = list(pageLength = 100,
                              scrollX = T,
                              filter = "top",
                              dom = "Bfrtip",
                              buttons = c("csv", "copy", "print")))
})
```
